# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'dingcan' do
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~> 3.7'
pod 'Masonry', '~> 0.6'
end

target 'dingcanTests' do

end

target 'dingcanUITests' do

end

